# Generated by Django 5.2 on 2025-04-28 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeOrdreMission',
            fields=[
                ('id_dem_ordre', models.AutoField(primary_key=True, serialize=False)),
                ('Message_ordre', models.TextField(blank=True, null=True)),
                ('Etat', models.CharField(choices=[('en_attente', 'En attente'), ('rejetee', 'Rejetée'), ('validee', 'Validée')], max_length=20)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Piece_jointe', models.FileField(blank=True, null=True, upload_to='ordres_mission/')),
                ('nom_employe', models.CharField(max_length=255)),
                ('poste', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('date_debut_mission', models.DateField()),
                ('date_fin_mission', models.DateField()),
                ('objet_mission', models.FileField(blank=True, null=True, upload_to='objets_mission/')),
                ('piece_identite', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('demandeur', 'Demandeur'), ('rh', 'RH')], max_length=20)),
                ('prenom_arabe', models.CharField(max_length=255)),
                ('nom_arabe', models.CharField(max_length=255)),
                ('eps_arabe', models.CharField(max_length=255)),
                ('nom_latin', models.CharField(max_length=255)),
                ('prenom_latin', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('femme', 'Femme'), ('homme', 'Homme')], max_length=10)),
                ('dateNais', models.DateField()),
                ('Lieu_Nais', models.CharField(max_length=255)),
                ('Grade', models.CharField(max_length=255)),
                ('Date1erEmbauche', models.DateField()),
                ('Stu_Adm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrdreMission',
            fields=[
                ('id_ordre_mission', models.AutoField(primary_key=True, serialize=False)),
                ('Moyens_transport', models.JSONField()),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField()),
                ('date_delivrance', models.DateField()),
                ('lieu_delivrance', models.CharField(max_length=255)),
                ('nom_respo', models.CharField(max_length=255)),
                ('prenom_respo', models.CharField(max_length=255)),
                ('dem_ordre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.demandeordremission')),
            ],
        ),
        migrations.AddField(
            model_name='demandeordremission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.user'),
        ),
        migrations.CreateModel(
            name='DemandeAttestation',
            fields=[
                ('id_dem_attest', models.AutoField(primary_key=True, serialize=False)),
                ('Message_dem_attest', models.TextField(blank=True, null=True)),
                ('Etat', models.CharField(choices=[('en_attente', 'En attente'), ('rejetee', 'Rejetée'), ('validee', 'Validée')], max_length=20)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Piece_jointe', models.FileField(blank=True, null=True, upload_to='attestations/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.user')),
            ],
        ),
    ]
