# Generated by Django 5.2 on 2025-05-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandeordremission",
            name="objet_mission",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ordremission",
            name="Moyens_transport",
            field=models.CharField(max_length=255),
        ),
    ]
