# Generated by Django 4.2.7 on 2025-05-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_passwordresetcode_delete_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temporary_role',
            field=models.CharField(blank=True, choices=[('rh', 'Ressources Humaines'), ('demandeur', 'Demandeur')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Date1erEmbauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Grade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Lieu_Nais',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Stu_Adm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateNais',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='eps_arabe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom_arabe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom_latin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom_arabe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom_latin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('rh', 'Ressources Humaines'), ('demandeur', 'Demandeur')], default='demandeur', max_length=20),
        ),
    ]
