# Generated by Django 5.2 on 2025-05-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_demandeordremission_objet_mission_and_more'),
        ('gestion', '0007_user_temporary_role_alter_user_date1erembauche_and_more'),
    ]

    operations = [
    ]
